### ISSUE TITLE
Brower Testing - Disable Images

### ISSUE THREAD

**Issue by char1129** [mato0039/web-design-2-independent-project#3]
Hi Cathy!

Good start on your website! I like the fonts you've chosen!
I see that you've started to add alt tags which is great! :) Remember to add proper descriptive descriptions like, so-and-so's logo.
Also to consider background colour as a placeholder for images that don't load, so that your site doesnt squish if they don't load.

Good luck! We're almost done!

Sarah

**Comment by mato0039** [comment]
Thank you so much Sarah! I appreciate the feedback. Have an awesome break! 
:)
