### ISSUE TITLE
Web Performance

### ISSUE THREAD

**Issue by lilbaj** [mato0039/web-design-2-independent-project#6]
<img width="1020" alt="Screen Shot 2020-12-11 at 2 29 12 PM" src="https://user-images.githubusercontent.com/55108804/101946708-4a84b180-3bbd-11eb-9bc6-c2ec590c7fa2.png">
<img width="1020" alt="Screen Shot 2020-12-11 at 2 29 21 PM" src="https://user-images.githubusercontent.com/55108804/101946711-4c4e7500-3bbd-11eb-8812-3d9725f2adff.png">

Hey, so you did great! this is an average score. im not sure how to fix the cashe issue but everyone has had a hard time with that so dw! great work!

**Comment by mato0039** [comment]
Thanks so much Lila!
Have a great break <3
